function tokenDetailPage(){return '<div id="token-detail" class="token-detail"><a class="token-back" href="/explore">← Explore tokens</a><div class="detail-loading" role="status">Loading token…</div></div>';}
function detailMoney(value){return value===null||value===undefined?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:value>=10000?'compact':'standard',maximumFractionDigits:value<.01?9:2}).format(value);}
function detailSol(value){return (Number(value)/1e9).toLocaleString('en-US',{maximumFractionDigits:9});}
function detailTokenAmount(value,decimals=6){return (Number(value)/10**decimals).toLocaleString('en-US',{maximumFractionDigits:4});}
function detailMarkup(t){return `<a class="token-back" href="/explore">← Explore tokens</a>
 <header class="token-detail-heading"><div class="token-identity"><div class="token-detail-art">${tokenImageMarkup(t,'',false)}</div><div><div class="token-name-line"><h1>${esc(t.name)}</h1><span class="token-ticker">$${esc(t.symbol)}</span></div><div class="token-identity-meta"><span class="pump-pill">${launchPumpIcon} ponsfamily.com</span><span>Launched <time title="${esc(new Date(t.created).toLocaleString())}">${tokenAge(t.created)}</time></span></div></div></div><div class="detail-recipients"><span class="detail-eyebrow">FEES SPLITX BETWEEN</span><div class="recipient-pills">${t.recipients.map(r=>`<a class="recipient-pill" href="https://x.com/${encodeURIComponent(r.handle)}" target="_blank" rel="noopener noreferrer" title="${r.share}% of the recipient allocation"><span class="recipient-x">𝕏</span><span>@${esc(r.handle)}</span><b>${r.share}%</b></a>`).join('')}</div></div></header>
 <div class="token-workspace"><div class="token-chart-column"><section class="market-stats" aria-label="Market statistics"><div><span>Price</span><strong id="market-price">—</strong></div><div><span id="market-cap-label">Market cap</span><strong id="market-cap">—</strong></div><div><span>24h volume</span><strong id="market-volume">—</strong></div><div><span>24h change</span><strong id="market-change">—</strong></div></section>
 <section class="token-chart-panel" aria-label="Token price chart"><div class="chart-heading"><div><span class="chart-symbol">${esc(t.symbol)} <span>/ USD</span></span><span class="chart-network">ponsfamily.com</span></div><span id="chart-data-status" class="chart-live-status" role="status" title="Automatically updates every 15 seconds while this page is visible.">Connecting</span></div>
 <div class="chart-toolbar"><div class="chart-intervals" role="group" aria-label="Chart interval">${['1m','3m','5m','15m','30m','1H','4H','1D'].map(id=>`<button type="button" data-chart-interval="${id}" aria-pressed="${id==='1m'}">${window.SplitexPayIntervalLabels[id]}</button>`).join('')}<details class="chart-more" id="chart-more"><summary aria-label="More chart timeframes"><span id="chart-more-label">More</span><span aria-hidden="true">⌄</span></summary><div class="chart-timeframe-menu">${['Seconds','Minutes','Hours','Days'].map(group=>`<div class="chart-timeframe-group"><span>${group}</span><div>${window.SplitexPayTimeframes.filter(i=>i.group===group).map(i=>`<button type="button" data-chart-interval="${i.id}" aria-pressed="${i.id==='1m'}">${i.label}</button>`).join('')}</div></div>`).join('')}</div></details></div><span class="chart-unit">USD</span></div>
 <div class="chart-ohlc" id="chart-ohlc" aria-label="Candle prices"><span>O <b data-ohlc="open">—</b></span><span>H <b data-ohlc="high">—</b></span><span>L <b data-ohlc="low">—</b></span><span>C <b data-ohlc="close">—</b></span></div>
 <div id="token-chart" class="token-chart"><div class="chart-placeholder" role="status"><span class="chart-loading-bars" aria-hidden="true"></span><p>Connecting to market data…</p></div></div><div class="chart-footer"><span id="chart-updated">Waiting for first update</span><span id="chart-source">UTC · Volume in USD</span></div><div class="chart-attribution"><span>Charts by <a href="https://www.tradingview.com/" target="_blank" rel="noopener noreferrer" title="TradingView Lightweight Charts™. Copyright (с) 2025 TradingView, Inc.">TradingView</a></span><a href="https://birdeye.so/token/${esc(t.mint)}?chain=solana" id="chart-data-link" target="_blank" rel="noopener noreferrer">Data: Birdeye ↗</a></div></section>
 <div id="market-updated" class="market-timestamp"></div>
 <section class="token-information"><div class="token-information-top"><h2>Token details</h2><a href="https://solscan.io/token/${esc(t.mint)}" target="_blank" rel="noopener noreferrer">Solscan ↗</a></div>${t.description?`<p class="token-description">${esc(t.description)}</p>`:''}<dl><div><dt>Contract</dt><dd><span class="detail-contract">${esc(t.mint)}</span><button class="token-copy" data-copy-mint="${esc(t.mint)}" aria-label="Copy contract address"><span>Copy CA</span></button></dd></div><div><dt>Launched</dt><dd>${esc(new Date(t.created).toLocaleString())}<a href="https://solscan.io/tx/${esc(t.signature)}" target="_blank" rel="noopener noreferrer">Transaction ↗</a></dd></div></dl><div class="token-social-links">${[['website','Website'],['x','𝕏'],['telegram','Telegram']].filter(([k])=>t.links[k]).map(([k,label])=>`<a href="${esc(t.links[k])}" target="_blank" rel="noopener noreferrer">${label} ↗</a>`).join('')}</div></section></div>
 <aside class="token-side-panel"><section class="token-buy-panel"><div class="buy-panel-heading"><h2>Buy ${esc(t.symbol)}</h2><span>Robinhood Chain</span></div><form id="token-buy-form" novalidate><div class="buy-amount-label"><label for="buy-amount">You pay</label><span id="buy-wallet-label">ETH</span></div><div class="buy-amount-field"><input id="buy-amount" name="amount" type="text" inputmode="decimal" autocomplete="off" placeholder="0.00" required aria-label="Amount of ETH to spend"><span><img src="/assets/solana-logo.svg" alt="" width="21" height="21"><b>ETH</b></span></div><div class="buy-presets">${['0.1','0.5','1','5'].map(n=>`<button type="button" data-buy-amount="${n}">${n} ETH</button>`).join('')}</div><div class="buy-setting"><label for="buy-slippage">Slippage tolerance</label><select id="buy-slippage" name="slippage"><option value="50">0.5%</option><option value="100" selected>1%</option><option value="300">3%</option></select></div><div id="buy-review" class="buy-review" hidden></div><p id="buy-status" class="buy-status" role="status" hidden></p><button id="token-buy-button" class="button buy-submit" type="submit">Connect wallet</button><button id="buy-reset" class="text-button" type="button" hidden>Change amount</button><p class="buy-wallet-note">You approve every purchase in your wallet.</p></form><a class="buy-external" href="https://ponsfamily.com/coin/${esc(t.mint)}" target="_blank" rel="noopener noreferrer">Trade on ponsfamily.com ↗</a></section>
 <section class="token-fee-panel"><h2>Creator fee allocation</h2><div class="fee-allocation-line"><span>X recipients</span><b>80%</b></div><div class="fee-allocation-line"><span>$SPLITX buybacks & burns</span><b>20%</b></div><div class="detail-fee-bar" aria-hidden="true"><span></span><span></span></div><p>Pill percentages divide the 80% recipient allocation. Automated payouts and buybacks are not enabled yet.</p><a href="/capital-flow">See the capital flow →</a></section></aside></div>`;}
function bindTokenDetail(mint){
 const root=document.querySelector('#token-detail'),controller=new AbortController();let stopped=false,marketTimer,marketController,quoteTimer,token=null,quote=null,working=false,chart=null,marketPair=null,chartInterval="1m",displayedInterval=null,chartSequence=0,candleTimer,chartController,intervalTimer;
 const $=id=>root.querySelector('#'+id);
 const pending=()=>window.SplitexPay?.tradePending?.mint===mint?window.SplitexPay.tradePending:null;
 function setStatus(text,error=false){const el=$('buy-status');if(!el)return;el.hidden=!text;el.textContent=text;el.classList.toggle('is-error',error);}
 function resetQuote(){quote=null;clearTimeout(quoteTimer);if($('buy-review'))$('buy-review').hidden=true;syncBuy();}
 function syncBuy(){if(stopped||!$('token-buy-button'))return;const busy=working||window.SplitexPay?.busy;const p=pending();$('token-buy-button').disabled=Boolean(busy);$('token-buy-button').textContent=working?'Please wait…':p?'Check purchase status':!window.SplitexPay?.address?'Connect wallet':quote?'Confirm buy':'Review buy';$('buy-amount').disabled=Boolean(busy||p||quote);$('buy-slippage').disabled=Boolean(busy||p||quote);root.querySelectorAll('[data-buy-amount]').forEach(b=>b.disabled=Boolean(busy||p||quote));$('buy-reset').hidden=!quote||Boolean(busy);const other=window.SplitexPay?.tradePending;if(other&&other.mint!==mint&&!working){$('buy-status').hidden=false;$('buy-status').innerHTML=`A previous purchase is pending. <a href="/token/${esc(other.mint)}">Check its status →</a>`;}$('buy-wallet-label').textContent=window.SplitexPay?.address?`${window.SplitexPay.address.slice(0,4)}…${window.SplitexPay.address.slice(-4)}`:'ETH';}
 function transactionStatus(result){if(stopped)return;resetQuote();if(result.confirmed){setStatus('Purchase confirmed. Tokens are in your wallet.');$('buy-review').hidden=false;$('buy-review').innerHTML=`<a href="https://solscan.io/tx/${esc(result.signature)}" target="_blank" rel="noopener noreferrer">View transaction ↗</a>`;}else if(result.failed){setStatus(result.error||'Purchase failed. You can review a new buy.',true);}else setStatus('Purchase submitted. Check its status before trying again.');syncBuy();}
 async function submit(e){e.preventDefault();if(working)return;if(!pending()&&!window.SplitexPay?.address){window.SplitexPay?.connect();return;}working=true;syncBuy();setStatus('');try{
  if(pending()){setStatus('Checking your purchase…');transactionStatus(await window.SplitexPay.checkTrade());}
  else if(quote){setStatus('Approve the purchase in your wallet…');transactionStatus(await window.SplitexPay.sendTrade(quote));}
  else {setStatus('Getting a quote and checking transaction costs…');const amount=$('buy-amount').value.trim(),slippage=Number($('buy-slippage').value);const result=await window.SplitexPay.quoteTrade({mint,amount,slippage});if(stopped)return;quote=result;$('buy-review').hidden=false;$('buy-review').innerHTML=`<div><span>You receive</span><strong>${detailTokenAmount(quote.tokenAmount,quote.decimals)} ${esc(token.symbol)}</strong></div><div><span>Maximum swap spend</span><strong>${detailSol(quote.maxSpend)} ETH</strong></div><div><span>Network fee</span><strong>${detailSol(quote.networkFee)} ETH</strong></div><div><span>Estimated total debit</span><strong>${detailSol(quote.estimatedDebit)} ETH</strong></div><p>Includes any token-account creation cost. Quote expires in 60 seconds.</p>`;setStatus('Review the amounts, then confirm in your wallet.');quoteTimer=setTimeout(()=>{resetQuote();setStatus('Quote expired. Review again for a fresh price.');},Math.max(0,quote.expires-Date.now()));}
 }catch(e){if(!stopped){resetQuote();setStatus(e?.code===4001||/reject|cancel/i.test(e.message)?'Purchase cancelled.':e.message||'Could not prepare your purchase. Please retry.',true);}}finally{working=false;syncBuy();}}
 function candleLegend(candle){if(!candle)return;root.querySelectorAll('[data-ohlc]').forEach(el=>{el.textContent=Number(candle[el.dataset.ohlc]).toLocaleString('en-US',{maximumSignificantDigits:5});});$('chart-ohlc').classList.toggle('is-down',candle.close<candle.open);}
 function chartStatus(text,live=false){$('chart-data-status').textContent=text;$('chart-data-status').classList.toggle('is-live',live);}
 async function refreshMarket(){if(stopped||!token||document.hidden)return;clearTimeout(marketTimer);marketController?.abort();marketController=new AbortController();const marketRequest=marketController;try{
  const response=await fetch(`/api/tokens/${mint}/market`,{signal:marketRequest.signal});const data=await response.json();if(!response.ok)throw new Error(data.error);if(stopped||document.hidden||marketRequest!==marketController)return;
  $('market-price').textContent=detailMoney(data.priceUsd);$('market-cap').textContent=detailMoney(data.marketCap??data.fdv);$('market-cap-label').textContent=data.marketCap!=null?'Market cap':'FDV';$('market-volume').textContent=detailMoney(data.volume24h);$('market-change').textContent=data.change24h==null?'—':`${data.change24h>0?'+':''}${data.change24h.toFixed(2)}%`;$('market-change').className=data.change24h==null?'':data.change24h>=0?'price-up':'price-down';
  if(data.available){marketPair=data.pair;$('market-updated').textContent=(data.stale?'Last market update ':'Market stats updated ')+new Date(data.updatedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});}
  else $('market-updated').textContent='Waiting for market statistics';
 }catch(e){if(!stopped&&!document.hidden&&marketRequest===marketController)$('market-updated').textContent='Market statistics reconnecting…';}finally{if(!stopped&&!document.hidden&&marketRequest===marketController)marketTimer=setTimeout(refreshMarket,30000);}}
 async function refreshCandles(){
  if(stopped||document.hidden)return;clearTimeout(candleTimer);chartController?.abort();chartController=new AbortController();const sequence=++chartSequence,requestedInterval=chartInterval,requestSignal=chartController.signal;let pollAfter=15000;
  if(!chart)chartStatus('Connecting');
  try{
   let data;try{const response=await fetch(`/api/tokens/${mint}/candles?interval=${requestedInterval}`,{signal:requestSignal});data=await response.json();if(!response.ok)throw new Error(data.error);}
   catch(error){if(requestSignal.aborted)throw error;data=await window.SplitexPayChartData(mint,requestedInterval,data?.pair||marketPair,requestSignal);}
   if(stopped||document.hidden||sequence!==chartSequence)return;pollAfter=Math.max(15000,Math.min(120000,Number(data.pollAfter)||15000));
   if(data.candles.length){
    if(chart&&displayedInterval===requestedInterval)chart.update(data.candles);else{chart?.remove();chart=window.SplitexPayChart($('token-chart'),data.candles,{secondsVisible:requestedInterval.endsWith('s'),onCandle:candleLegend});}
    displayedInterval=requestedInterval;root.querySelectorAll('[data-chart-interval]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.chartInterval===displayedInterval)));
    $('chart-more-label').textContent=['1m','3m','5m','15m','30m','1H','4H','1D'].includes(displayedInterval)?'More':window.SplitexPayIntervalLabels[displayedInterval];
    chartStatus(data.stale?'Reconnecting':'Live',!data.stale);$('chart-data-status').title=data.stale?'Showing the last available candles while reconnecting.':`Updates automatically every ${pollAfter/1000} seconds while visible.`;
    $('chart-updated').textContent=(data.stale?'Last available update ':'Updated ')+new Date(data.updatedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'});
   }else if(!chart){$('token-chart').innerHTML='<div class="chart-placeholder"><p>Waiting for first trades</p><small>The chart will appear automatically when trades are indexed.</small></div>';chartStatus('Awaiting trades');}
   $('chart-data-link').textContent=`Data: ${data.source} ↗`;$('chart-data-link').href=data.source==='Birdeye'?`https://birdeye.so/token/${mint}?chain=solana`:`https://www.geckoterminal.com/solana/pools/${encodeURIComponent(data.pair||marketPair)}`;
  }catch(e){if(!stopped&&!document.hidden&&sequence===chartSequence){chartStatus('Reconnecting');if(chart){chartInterval=displayedInterval;$('chart-updated').textContent='Showing last available '+window.SplitexPayIntervalLabels[displayedInterval]+' chart';}else $('token-chart').innerHTML='<div class="chart-placeholder"><span class="chart-loading-bars" aria-hidden="true"></span><p>Reconnecting to market data…</p><small>This chart retries automatically.</small></div>';}}
  finally{if(!stopped&&!document.hidden&&sequence===chartSequence)candleTimer=setTimeout(refreshCandles,pollAfter);}
 }
 function selectInterval(button){$('chart-more').open=false;const interval=button.dataset.chartInterval;if(interval===chartInterval)return;chartInterval=interval;clearTimeout(candleTimer);clearTimeout(intervalTimer);chartController?.abort();chartSequence++;$('chart-more').open=false;chartStatus('Loading '+window.SplitexPayIntervalLabels[interval]);intervalTimer=setTimeout(refreshCandles,180);}
 const onWallet=()=>{if(quote&&quote.wallet!==window.SplitexPay?.address)resetQuote();syncBuy();};
 const onVisible=()=>{if(document.hidden){clearTimeout(marketTimer);clearTimeout(candleTimer);clearTimeout(intervalTimer);marketController?.abort();chartController?.abort();chartSequence++;}else if(token){refreshMarket();refreshCandles();}};
 (async()=>{try{const response=await fetch(`/api/tokens/${encodeURIComponent(mint)}`,{signal:controller.signal});const result=await response.json();if(!response.ok)throw new Error(result.error||'Unable to load this token.');if(stopped)return;token=result.token;root.innerHTML=detailMarkup(token);document.title=`${token.name} ($${token.symbol}) - SplitexPay`;bindTokenCards(root);root.querySelectorAll('[data-buy-amount]').forEach(b=>b.onclick=()=>{$('buy-amount').value=b.dataset.buyAmount;resetQuote();setStatus('');});$('buy-reset').onclick=()=>{resetQuote();setStatus('');};$('token-buy-form').onsubmit=submit;root.querySelectorAll('[data-chart-interval]').forEach(b=>b.onclick=()=>selectInterval(b));$('chart-more').addEventListener('keydown',e=>{if(e.key==='Escape'){$('chart-more').open=false;$('chart-more').querySelector('summary').focus();}});syncBuy();refreshMarket();refreshCandles();}catch(e){if(!stopped)root.innerHTML=`<a class="token-back" href="/explore">← Explore tokens</a><section class="home-empty"><h1>Unable to open token</h1><p>${esc(e.message)}</p><a class="button" href="/explore">Back to Explore</a></section>`;}})();
 document.addEventListener('splitexpay:wallet',onWallet);document.addEventListener('visibilitychange',onVisible);
 return()=>{stopped=true;controller.abort();marketController?.abort();chartController?.abort();clearTimeout(intervalTimer);chart?.remove();clearTimeout(candleTimer);clearTimeout(marketTimer);clearTimeout(quoteTimer);document.removeEventListener('splitexpay:wallet',onWallet);document.removeEventListener('visibilitychange',onVisible);};
}
